### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by alexbriskin** [superjer/vimtutor-extended#3]

**Comment by superjer** [comment]
Do you have a suggested license? I don't know what license is used in the original vimtutor, or I'd re-use that.

**Comment by alexbriskin** [comment]
I guess it is under the same licence as vim itself.
Also adding a license in github is really easy. You can add a new file call it licence and GitHub lets you choose from scroll down menu several standard licenses. GNU v2 license is very common.

**Comment by superjer** [comment]
OK the Vim license doesn't seem appropriate now that I read it.

So I'm using GPLv2 instead.
